### ISSUE TITLE
ValueError: could not broadcast input array from shape (18) into shape (4000)

### ISSUE THREAD

**Issue by ceryshughes** [lifengjin/dimi_emnlp18#1]
Tried running out of the box on the example data and config file on a personal laptop.
C:\Users\Cerys\Anaconda3\python.exe C:/Users/Cerys/PycharmProjects/dimi_emnlp18/dimi-trainer.py C:\Users\Cerys\PycharmProjects\dimi_emnlp18\config\config.ini
spawn
The output directory for this run is ./outputs/abbabbc_D2K3A0.2_2.
09/24/2018 09:43:46 AM Using default seed for random number generator.
09/24/2018 09:43:46 AM Total number of tokens: 950, number of nodes: 1900
09/24/2018 09:43:46 AM Initializing state: K is 3; D is 2; MaxLen is 7
09/24/2018 09:43:46 AM PCFG translator NULL initialization.
09/24/2018 09:43:46 AM PCFG model sampling.
09/24/2018 09:43:46 AM Dumping out the pcfg model takes 0.030 secs.
09/24/2018 09:43:46 AM resample the pcfg model with nonterm alpha 0.2, term alpha 0.2 and annealing coeff 1.0.
09/24/2018 09:43:46 AM Converting to delta
09/24/2018 09:43:46 AM Converting to gamma
09/24/2018 09:43:46 AM Bounded model setting the models
09/24/2018 09:43:46 AM Dumping out the bounded models
09/24/2018 09:43:46 AM GPU is False with 0 workers and batch size 25
09/24/2018 09:43:46 AM Start a new worker with python3 scripts/workers.py 192.168.56.1 61141 61153 61167 8 0 25
09/24/2018 09:43:46 AM Starting workers
09/24/2018 09:43:46 AM Starting workers with maxLen=7 and num_cpu_workers=2 and num_gpu_workers=0
09/24/2018 09:43:46 AM Starting 2 cpu workers and 0 gpu workers at host 192.168.56.1 with jobs_port=61141, results_port=61153, models_port=61167, maxLen=7
09/24/2018 09:43:46 AM Parsing started Now. Sink loading the sentences.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Cerys\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Cerys\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\PyzmqWorker.py", line 72, in run
    self.cky_sampler = CKY_sampler(K=self.K, D=self.D, max_len=self.max_len, gpu=self.gpu)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\cky_sampler_inner.py", line 10, in __init__
    assert D != 0 and K != 0, 'Sampler initialization error: K {}, D {}'.format(K, D)
AssertionError: Sampler initialization error: K 1000, D 0
WARNING:root:Warning: Sentence 0 had a parsing error could not broadcast input array from shape (18) into shape (4000).
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Cerys\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Cerys\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\PyzmqWorker.py", line 101, in run
    self.processSentences(jobs_socket, results_socket)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\PyzmqWorker.py", line 191, in processSentences
    sent)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\cky_sampler_inner.py", line 150, in inside_sample
    self.compute_inside(sent)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\cky_sampler_inner.py", line 244, in compute_inside
    np.copyto(self.chart[i, i+1], self.lexis[w])
ValueError: could not broadcast input array from shape (18) into shape (4000)

**Comment by lifengjin** [comment]
It has something to do with how a process is spawned on Windows, which is different from Unix. I made a fix. Can you try it out? I have no Windows machine.

**Comment by ceryshughes** [comment]
Thanks! I pulled the fix into my local copy and ran it again, but it's still producing a runtime error that I think is the same as the original one:

C:\Users\Cerys\Anaconda3\python.exe C:/Users/Cerys/PycharmProjects/dimi_emnlp18/dimi-trainer.py C:\Users\Cerys\PycharmProjects\dimi_emnlp18\config\config.ini
spawn
The output directory for this run is ./outputs/abbabbc_D2K3A0.2_6.
09/24/2018 12:51:25 PM Using default seed for random number generator.
09/24/2018 12:51:25 PM Total number of tokens: 950, number of nodes: 1900
09/24/2018 12:51:25 PM Initializing state: K is 3; D is 2; MaxLen is 7
09/24/2018 12:51:25 PM PCFG translator NULL initialization.
09/24/2018 12:51:25 PM PCFG model sampling.
09/24/2018 12:51:25 PM Dumping out the pcfg model takes 0.010 secs.
09/24/2018 12:51:25 PM resample the pcfg model with nonterm alpha 0.2, term alpha 0.2 and annealing coeff 1.0.
09/24/2018 12:51:25 PM Converting to delta
09/24/2018 12:51:25 PM Converting to gamma
09/24/2018 12:51:25 PM Bounded model setting the models
09/24/2018 12:51:25 PM Dumping out the bounded models
09/24/2018 12:51:25 PM GPU is False with 0 workers and batch size 25
09/24/2018 12:51:25 PM Start a new worker with python3 scripts/workers.py 192.168.56.1 55782 55794 55808 8 0 25
09/24/2018 12:51:25 PM Starting workers
09/24/2018 12:51:25 PM Starting workers with maxLen=7 and num_cpu_workers=2 and num_gpu_workers=0
09/24/2018 12:51:25 PM Starting 2 cpu workers and 0 gpu workers at host 192.168.56.1 with jobs_port=55782, results_port=55794, models_port=55808, maxLen=7
09/24/2018 12:51:25 PM Parsing started Now. Sink loading the sentences.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Cerys\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Cerys\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\workers.py", line 36, in worker_run_proxy
    worker.run()
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\PyzmqWorker.py", line 72, in run
    self.cky_sampler = CKY_sampler(K=self.K, D=self.D, max_len=self.max_len, gpu=self.gpu)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\cky_sampler_inner.py", line 10, in __init__
    assert D != 0 and K != 0, 'Sampler initialization error: K {}, D {}'.format(K, D)
AssertionError: Sampler initialization error: K 1000, D 0
WARNING:root:Warning: Sentence 0 had a parsing error could not broadcast input array from shape (18) into shape (4000).
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Cerys\Anaconda3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Cerys\Anaconda3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\workers.py", line 36, in worker_run_proxy
    worker.run()
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\PyzmqWorker.py", line 101, in run
    self.processSentences(jobs_socket, results_socket)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\PyzmqWorker.py", line 191, in processSentences
    sent)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\cky_sampler_inner.py", line 150, in inside_sample
    self.compute_inside(sent)
  File "C:\Users\Cerys\PycharmProjects\dimi_emnlp18\scripts\cky_sampler_inner.py", line 244, in compute_inside
    np.copyto(self.chart[i, i+1], self.lexis[w])
ValueError: could not broadcast input array from shape (18) into shape (4000)

**Comment by lifengjin** [comment]
It should have been fixed. Can you try again?

**Comment by ceryshughes** [comment]
Yep, I tried again and it seems to be working now. Thanks!
